# Minimal git-cliff configuration

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

"""

[git]
conventional_commits = true
filter_unconventional = true